FROM azul/zulu-openjdk:8

WORKDIR /home/midnight
# Make the script executable
RUN chmod +x /home/midnight/start.sh

# Adjust CMD instruction
CMD chmod +x /home/midnight/start.sh ; /home/midnight/start.sh
