# Credits to https://github.com/sparkedhost/images/ :D
name: Build java-8
on:
  push:
    branches:
      - main
    paths:
      - java/java-8/*
      - .github/workflows/java-8.yml
jobs:
  push:
    name: "java-8"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./java/java-8/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/nekocraftnw/images:java-8
